<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <title><?php echo $title ? $title : 'Project Hand Off'; ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type="text/css">
        <?php echo $css; ?>
    </style>
</head>

<body>
    <div id="holderFixed">

        <?php echo $logo; ?>
            
        <h5>
            <?php echo $project['title']; ?><?php if ($title) {
    echo ': ' . $title;
} ?>
        </h5>

        <div class="border">
            <div class="borderSection pad sunk">
                
                <table width="100%">
                    <tr>
                        <th><b>Contractor</b></th>
                        <th><b>Client</b></th>
                    </tr>
                    <tr>
                        <td width="50%" valign="top">
                            <b><?php echo $company['title']; ?></b><br />
                            <?php echo $company['address']; ?>
                        </td>
                        <td width="50%" valign="top">
                            <b><?php echo $client['title']; ?></b><br />
                            <?php echo $client['address']; ?>
                        </td>
                    </tr>
                </table>
            </div>

            <?php if (!empty($message)) { ?>
                <div class="sunk columns2575 pad">
                    <div class="textRight">
                        <h4>Details</h4>
                    </div>
                    <div>
                        <?php echo $message; ?>
                    </div>
                </div>
            <?php } ?>
            
            <div class="borderSectionTop">
                <table width="100%" style="font-size:90%;verticle-align:middle;">
                    <thead>
                        <tr class="noHighlight">
                            <th width="100">Date</th>
                            <th width="">Task</th>
                            <th width="100">Units</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $totalHours = 0;
                        foreach ($stories as $aStory) {
                            $totalHours += $aStory['hours'];
                            $date = formatDate($aStory['ended_at']);
                        ?>
                            <tr>
                                <td>
                                    <?php echo $date; ?>
                                </td>
                                <td>
                                    <?php echo $aStory['title']; ?>
                                </td>
                                <td>
                                    <?php echo $aStory['hours']; ?>
                                </td>
                            </tr>
                        <?php } ?>
                        <tr>
                            <td></td>
                            <td></td>
                            <td class="bold"><?php echo $totalHours; ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="invoiceFooter">This invoice was generated by <a
                href="https://github.com/jbelelieu/atos" target="_blank">ATOS
                software</a>.</div>
    </div>
</body>
</html>