<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <title><?php echo $project['title']; ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type="text/css">
        <?php echo $css; ?>
    </style>
</head>

<body>
    <div id="holderFixed">

        <?php echo $logo; ?>
            
        <h3>
            <?php if ($title) { ?>
                <?php echo $title; ?>
            <?php } else { ?>
                <?php echo $project['title']; ?>
            <?php } ?>
        </h3>
        
        <div class="border">
            <div class="borderSection pad">
                
                <table width="100%">
                    <tr>
                        <th><b>Billing Party</b></th>
                        <th><b>Bill To</b></th>
                    </tr>
                    <tr>
                        <td width="50%" valign="top">
                            <b><?php echo $company['title']; ?></b><br />
                            <?php echo $company['address']; ?>
                        </td>
                        <td width="50%" valign="top">
                            <b><?php echo $client['title']; ?></b><br />
                            <?php echo $client['address']; ?>
                        </td>
                    </tr>
                </table>
            </div>

            <?php if (!empty($message)) { ?>
                <div class="sunk columns2575 pad">
                    <div class="textRight">
                        <h4>Details</h4>
                    </div>
                    <div>
                        <?php echo $message; ?>
                    </div>
                </div>
            <?php } ?>
            
            <div class="borderSectionTop">
                <table width="100%" style="font-size:90%;">
                    <thead>
                        <tr>
                            <th width="">Task</th>
                            <th width="155">Type</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($stories as $aStory) { ?>
                            <tr>
                                <td>
                                    <?php echo $aStory['title']; ?>
                                </td>
                                <td>
                                    <?php echo $aStory['typeTitle']; ?>
                                </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="invoiceFooter">This invoice was generated by <a
                href="https://github.com/jbelelieu/atos" target="_blank">ATOS
                software</a>.</div>
    </div>
</body>
</html>